#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSBanchileSEGUROS
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BANCHILE_CMS")]
	public partial class Banchile_CMSDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public Banchile_CMSDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Banchile_CMSDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Banchile_CMSDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Banchile_CMSDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_CMS_Categoria_Actualizar")]
		public int usp_CMS_Categoria_Actualizar([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdCategoria", DbType="Int")] System.Nullable<int> idCategoria, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="NVarChar(100)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="NVarChar(250)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdCategoriaPadre", DbType="Int")] System.Nullable<int> idCategoriaPadre)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idCategoria, nombre, descripcion, idCategoriaPadre);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_CMS_UsuarioRol_QuitarPorIds")]
		public int usp_CMS_UsuarioRol_QuitarPorIds([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="Int")] System.Nullable<int> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdRol", DbType="Int")] System.Nullable<int> idRol)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuario, idRol);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_CMS_Categoria_Crear")]
		public ISingleResult<usp_CMS_Categoria_CrearResult> usp_CMS_Categoria_Crear([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="NVarChar(100)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="NVarChar(250)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdCategoriaPadre", DbType="Int")] System.Nullable<int> idCategoriaPadre)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre, descripcion, idCategoriaPadre);
			return ((ISingleResult<usp_CMS_Categoria_CrearResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_CMS_Categoria_Eliminar")]
		public int usp_CMS_Categoria_Eliminar([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdCategoria", DbType="Int")] System.Nullable<int> idCategoria)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idCategoria);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_CMS_Categoria_Listar")]
		public ISingleResult<usp_CMS_Categoria_ListarResult> usp_CMS_Categoria_Listar()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<usp_CMS_Categoria_ListarResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_CMS_Categoria_ObtenerPorId")]
		public ISingleResult<usp_CMS_Categoria_ObtenerPorIdResult> usp_CMS_Categoria_ObtenerPorId([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdCategoria", DbType="Int")] System.Nullable<int> idCategoria)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idCategoria);
			return ((ISingleResult<usp_CMS_Categoria_ObtenerPorIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_CMS_Contenido_Actualizar")]
		public int usp_CMS_Contenido_Actualizar([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdContenido", DbType="Int")] System.Nullable<int> idContenido, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Titulo", DbType="NVarChar(200)")] string titulo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CuerpoHTML", DbType="NVarChar(MAX)")] string cuerpoHTML, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdCategoria", DbType="Int")] System.Nullable<int> idCategoria, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Estado", DbType="VarChar(20)")] string estado, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuarioAutor", DbType="Int")] System.Nullable<int> idUsuarioAutor, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EsDestacado", DbType="Bit")] System.Nullable<bool> esDestacado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idContenido, titulo, cuerpoHTML, idCategoria, estado, idUsuarioAutor, esDestacado);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_CMS_Contenido_Crear")]
		public ISingleResult<usp_CMS_Contenido_CrearResult> usp_CMS_Contenido_Crear([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Titulo", DbType="NVarChar(200)")] string titulo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CuerpoHTML", DbType="NVarChar(MAX)")] string cuerpoHTML, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdCategoria", DbType="Int")] System.Nullable<int> idCategoria, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Estado", DbType="VarChar(20)")] string estado, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuarioAutor", DbType="Int")] System.Nullable<int> idUsuarioAutor, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EsDestacado", DbType="Bit")] System.Nullable<bool> esDestacado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), titulo, cuerpoHTML, idCategoria, estado, idUsuarioAutor, esDestacado);
			return ((ISingleResult<usp_CMS_Contenido_CrearResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_CMS_Contenido_Eliminar")]
		public int usp_CMS_Contenido_Eliminar([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdContenido", DbType="Int")] System.Nullable<int> idContenido)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idContenido);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_CMS_Contenido_Listar")]
		public ISingleResult<usp_CMS_Contenido_ListarResult> usp_CMS_Contenido_Listar()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<usp_CMS_Contenido_ListarResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_CMS_Contenido_ListarPorCategoria")]
		public ISingleResult<usp_CMS_Contenido_ListarPorCategoriaResult> usp_CMS_Contenido_ListarPorCategoria([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdCategoria", DbType="Int")] System.Nullable<int> idCategoria)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idCategoria);
			return ((ISingleResult<usp_CMS_Contenido_ListarPorCategoriaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_CMS_Contenido_ObtenerPorId")]
		public ISingleResult<usp_CMS_Contenido_ObtenerPorIdResult> usp_CMS_Contenido_ObtenerPorId([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdContenido", DbType="Int")] System.Nullable<int> idContenido)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idContenido);
			return ((ISingleResult<usp_CMS_Contenido_ObtenerPorIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_CMS_ContenidoMultimedia_Asignar")]
		public ISingleResult<usp_CMS_ContenidoMultimedia_AsignarResult> usp_CMS_ContenidoMultimedia_Asignar([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdContenido", DbType="Int")] System.Nullable<int> idContenido, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdArchivo", DbType="Int")] System.Nullable<int> idArchivo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idContenido, idArchivo);
			return ((ISingleResult<usp_CMS_ContenidoMultimedia_AsignarResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_CMS_ContenidoMultimedia_ListarPorContenido")]
		public ISingleResult<usp_CMS_ContenidoMultimedia_ListarPorContenidoResult> usp_CMS_ContenidoMultimedia_ListarPorContenido([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdContenido", DbType="Int")] System.Nullable<int> idContenido)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idContenido);
			return ((ISingleResult<usp_CMS_ContenidoMultimedia_ListarPorContenidoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_CMS_ContenidoMultimedia_ObtenerPorId")]
		public ISingleResult<usp_CMS_ContenidoMultimedia_ObtenerPorIdResult> usp_CMS_ContenidoMultimedia_ObtenerPorId([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdContenidoMultimedia", DbType="Int")] System.Nullable<int> idContenidoMultimedia)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idContenidoMultimedia);
			return ((ISingleResult<usp_CMS_ContenidoMultimedia_ObtenerPorIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_CMS_ContenidoMultimedia_Quitar")]
		public int usp_CMS_ContenidoMultimedia_Quitar([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdContenidoMultimedia", DbType="Int")] System.Nullable<int> idContenidoMultimedia)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idContenidoMultimedia);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_CMS_ContenidoRol_ActualizarPermiso")]
		public int usp_CMS_ContenidoRol_ActualizarPermiso([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdContenidoRol", DbType="Int")] System.Nullable<int> idContenidoRol, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Permiso", DbType="VarChar(50)")] string permiso)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idContenidoRol, permiso);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_CMS_ContenidoRol_AsignarPermiso")]
		public ISingleResult<usp_CMS_ContenidoRol_AsignarPermisoResult> usp_CMS_ContenidoRol_AsignarPermiso([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdContenido", DbType="Int")] System.Nullable<int> idContenido, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdRol", DbType="Int")] System.Nullable<int> idRol, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Permiso", DbType="VarChar(50)")] string permiso)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idContenido, idRol, permiso);
			return ((ISingleResult<usp_CMS_ContenidoRol_AsignarPermisoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_CMS_ContenidoRol_ListarPorContenido")]
		public ISingleResult<usp_CMS_ContenidoRol_ListarPorContenidoResult> usp_CMS_ContenidoRol_ListarPorContenido([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdContenido", DbType="Int")] System.Nullable<int> idContenido)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idContenido);
			return ((ISingleResult<usp_CMS_ContenidoRol_ListarPorContenidoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_CMS_ContenidoRol_ObtenerPorId")]
		public ISingleResult<usp_CMS_ContenidoRol_ObtenerPorIdResult> usp_CMS_ContenidoRol_ObtenerPorId([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdContenidoRol", DbType="Int")] System.Nullable<int> idContenidoRol)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idContenidoRol);
			return ((ISingleResult<usp_CMS_ContenidoRol_ObtenerPorIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_CMS_ContenidoRol_QuitarPermiso")]
		public int usp_CMS_ContenidoRol_QuitarPermiso([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdContenidoRol", DbType="Int")] System.Nullable<int> idContenidoRol)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idContenidoRol);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_CMS_HistorialContenido_ListarPorContenido")]
		public ISingleResult<usp_CMS_HistorialContenido_ListarPorContenidoResult> usp_CMS_HistorialContenido_ListarPorContenido([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdContenido", DbType="Int")] System.Nullable<int> idContenido)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idContenido);
			return ((ISingleResult<usp_CMS_HistorialContenido_ListarPorContenidoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_CMS_HistorialContenido_ObtenerPorId")]
		public ISingleResult<usp_CMS_HistorialContenido_ObtenerPorIdResult> usp_CMS_HistorialContenido_ObtenerPorId([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdHistorial", DbType="Int")] System.Nullable<int> idHistorial)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idHistorial);
			return ((ISingleResult<usp_CMS_HistorialContenido_ObtenerPorIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_CMS_HistorialContenido_Registrar")]
		public ISingleResult<usp_CMS_HistorialContenido_RegistrarResult> usp_CMS_HistorialContenido_Registrar([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdContenido", DbType="Int")] System.Nullable<int> idContenido, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="Int")] System.Nullable<int> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Comentario", DbType="NVarChar(250)")] string comentario)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idContenido, idUsuario, comentario);
			return ((ISingleResult<usp_CMS_HistorialContenido_RegistrarResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_CMS_Multimedia_Actualizar")]
		public int usp_CMS_Multimedia_Actualizar([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdArchivo", DbType="Int")] System.Nullable<int> idArchivo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NombreOriginal", DbType="NVarChar(200)")] string nombreOriginal)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idArchivo, nombreOriginal);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_CMS_Multimedia_Crear")]
		public ISingleResult<usp_CMS_Multimedia_CrearResult> usp_CMS_Multimedia_Crear([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NombreOriginal", DbType="NVarChar(200)")] string nombreOriginal, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ArchivoBase64", DbType="Text")] string archivoBase64, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TipoMIME", DbType="VarChar(100)")] string tipoMIME, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuarioSubio", DbType="Int")] System.Nullable<int> idUsuarioSubio)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombreOriginal, archivoBase64, tipoMIME, idUsuarioSubio);
			return ((ISingleResult<usp_CMS_Multimedia_CrearResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_CMS_Multimedia_Eliminar")]
		public int usp_CMS_Multimedia_Eliminar([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdArchivo", DbType="Int")] System.Nullable<int> idArchivo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idArchivo);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_CMS_Multimedia_Listar")]
		public ISingleResult<usp_CMS_Multimedia_ListarResult> usp_CMS_Multimedia_Listar()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<usp_CMS_Multimedia_ListarResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_CMS_Multimedia_ObtenerPorId")]
		public ISingleResult<usp_CMS_Multimedia_ObtenerPorIdResult> usp_CMS_Multimedia_ObtenerPorId([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdArchivo", DbType="Int")] System.Nullable<int> idArchivo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idArchivo);
			return ((ISingleResult<usp_CMS_Multimedia_ObtenerPorIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_CMS_Rol_Actualizar")]
		public int usp_CMS_Rol_Actualizar([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdRol", DbType="Int")] System.Nullable<int> idRol, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NombreRol", DbType="NVarChar(100)")] string nombreRol, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="NVarChar(250)")] string descripcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idRol, nombreRol, descripcion);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_CMS_Rol_Crear")]
		public ISingleResult<usp_CMS_Rol_CrearResult> usp_CMS_Rol_Crear([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NombreRol", DbType="NVarChar(100)")] string nombreRol, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="NVarChar(250)")] string descripcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombreRol, descripcion);
			return ((ISingleResult<usp_CMS_Rol_CrearResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_CMS_Rol_Eliminar")]
		public int usp_CMS_Rol_Eliminar([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdRol", DbType="Int")] System.Nullable<int> idRol)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idRol);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_CMS_Rol_Listar")]
		public ISingleResult<usp_CMS_Rol_ListarResult> usp_CMS_Rol_Listar()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<usp_CMS_Rol_ListarResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_CMS_Rol_ObtenerPorId")]
		public ISingleResult<usp_CMS_Rol_ObtenerPorIdResult> usp_CMS_Rol_ObtenerPorId([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdRol", DbType="Int")] System.Nullable<int> idRol)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idRol);
			return ((ISingleResult<usp_CMS_Rol_ObtenerPorIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_CMS_Usuario_Actualizar")]
		public int usp_CMS_Usuario_Actualizar([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="Int")] System.Nullable<int> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NombreCompleto", DbType="NVarChar(200)")] string nombreCompleto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Usuario", DbType="NVarChar(100)")] string usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Password", DbType="NVarChar(200)")] string password)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuario, nombreCompleto, usuario, password);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_CMS_Usuario_Crear")]
		public ISingleResult<usp_CMS_Usuario_CrearResult> usp_CMS_Usuario_Crear([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NombreCompleto", DbType="NVarChar(200)")] string nombreCompleto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Usuario", DbType="NVarChar(100)")] string usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Password", DbType="NVarChar(200)")] string password)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombreCompleto, usuario, password);
			return ((ISingleResult<usp_CMS_Usuario_CrearResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_CMS_Usuario_Eliminar")]
		public int usp_CMS_Usuario_Eliminar([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="Int")] System.Nullable<int> idUsuario)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuario);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_CMS_Usuario_Listar")]
		public ISingleResult<usp_CMS_Usuario_ListarResult> usp_CMS_Usuario_Listar()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<usp_CMS_Usuario_ListarResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_CMS_Usuario_ObtenerPorId")]
		public ISingleResult<usp_CMS_Usuario_ObtenerPorIdResult> usp_CMS_Usuario_ObtenerPorId([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="Int")] System.Nullable<int> idUsuario)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuario);
			return ((ISingleResult<usp_CMS_Usuario_ObtenerPorIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_CMS_Usuario_ValidarLogin")]
		public ISingleResult<usp_CMS_Usuario_ValidarLoginResult> usp_CMS_Usuario_ValidarLogin([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Usuario", DbType="NVarChar(100)")] string usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Password", DbType="NVarChar(200)")] string password)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), usuario, password);
			return ((ISingleResult<usp_CMS_Usuario_ValidarLoginResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_CMS_UsuarioRol_Asignar")]
		public ISingleResult<usp_CMS_UsuarioRol_AsignarResult> usp_CMS_UsuarioRol_Asignar([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="Int")] System.Nullable<int> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdRol", DbType="Int")] System.Nullable<int> idRol)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuario, idRol);
			return ((ISingleResult<usp_CMS_UsuarioRol_AsignarResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_CMS_UsuarioRol_ListarPorUsuario")]
		public ISingleResult<usp_CMS_UsuarioRol_ListarPorUsuarioResult> usp_CMS_UsuarioRol_ListarPorUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="Int")] System.Nullable<int> idUsuario)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuario);
			return ((ISingleResult<usp_CMS_UsuarioRol_ListarPorUsuarioResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_CMS_UsuarioRol_ObtenerPorId")]
		public ISingleResult<usp_CMS_UsuarioRol_ObtenerPorIdResult> usp_CMS_UsuarioRol_ObtenerPorId([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuarioRol", DbType="Int")] System.Nullable<int> idUsuarioRol)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuarioRol);
			return ((ISingleResult<usp_CMS_UsuarioRol_ObtenerPorIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_CMS_UsuarioRol_Quitar")]
		public int usp_CMS_UsuarioRol_Quitar([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuarioRol", DbType="Int")] System.Nullable<int> idUsuarioRol)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuarioRol);
			return ((int)(result.ReturnValue));
		}
	}
	
	public partial class usp_CMS_Categoria_CrearResult
	{
		
		private System.Nullable<decimal> _IdCategoriaCreada;
		
		public usp_CMS_Categoria_CrearResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCategoriaCreada", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> IdCategoriaCreada
		{
			get
			{
				return this._IdCategoriaCreada;
			}
			set
			{
				if ((this._IdCategoriaCreada != value))
				{
					this._IdCategoriaCreada = value;
				}
			}
		}
	}
	
	public partial class usp_CMS_Categoria_ListarResult
	{
		
		private int _IdCategoria;
		
		private string _Nombre;
		
		private string _Descripcion;
		
		private System.Nullable<int> _IdCategoriaPadre;
		
		public usp_CMS_Categoria_ListarResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCategoria", DbType="Int NOT NULL")]
		public int IdCategoria
		{
			get
			{
				return this._IdCategoria;
			}
			set
			{
				if ((this._IdCategoria != value))
				{
					this._IdCategoria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="NVarChar(250)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCategoriaPadre", DbType="Int")]
		public System.Nullable<int> IdCategoriaPadre
		{
			get
			{
				return this._IdCategoriaPadre;
			}
			set
			{
				if ((this._IdCategoriaPadre != value))
				{
					this._IdCategoriaPadre = value;
				}
			}
		}
	}
	
	public partial class usp_CMS_Categoria_ObtenerPorIdResult
	{
		
		private int _IdCategoria;
		
		private string _Nombre;
		
		private string _Descripcion;
		
		private System.Nullable<int> _IdCategoriaPadre;
		
		public usp_CMS_Categoria_ObtenerPorIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCategoria", DbType="Int NOT NULL")]
		public int IdCategoria
		{
			get
			{
				return this._IdCategoria;
			}
			set
			{
				if ((this._IdCategoria != value))
				{
					this._IdCategoria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="NVarChar(250)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCategoriaPadre", DbType="Int")]
		public System.Nullable<int> IdCategoriaPadre
		{
			get
			{
				return this._IdCategoriaPadre;
			}
			set
			{
				if ((this._IdCategoriaPadre != value))
				{
					this._IdCategoriaPadre = value;
				}
			}
		}
	}
	
	public partial class usp_CMS_Contenido_CrearResult
	{
		
		private System.Nullable<decimal> _IdContenidoCreado;
		
		public usp_CMS_Contenido_CrearResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdContenidoCreado", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> IdContenidoCreado
		{
			get
			{
				return this._IdContenidoCreado;
			}
			set
			{
				if ((this._IdContenidoCreado != value))
				{
					this._IdContenidoCreado = value;
				}
			}
		}
	}
	
	public partial class usp_CMS_Contenido_ListarResult
	{
		
		private int _IdContenido;
		
		private string _Titulo;
		
		private string _CuerpoHTML;
		
		private System.Nullable<int> _IdCategoria;
		
		private string _Estado;
		
		private System.Nullable<System.DateTime> _FechaCreacion;
		
		private System.Nullable<System.DateTime> _FechaModificacion;
		
		private System.Nullable<int> _IdUsuarioAutor;
		
		private System.Nullable<bool> _EsDestacado;
		
		public usp_CMS_Contenido_ListarResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdContenido", DbType="Int NOT NULL")]
		public int IdContenido
		{
			get
			{
				return this._IdContenido;
			}
			set
			{
				if ((this._IdContenido != value))
				{
					this._IdContenido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Titulo", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string Titulo
		{
			get
			{
				return this._Titulo;
			}
			set
			{
				if ((this._Titulo != value))
				{
					this._Titulo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CuerpoHTML", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string CuerpoHTML
		{
			get
			{
				return this._CuerpoHTML;
			}
			set
			{
				if ((this._CuerpoHTML != value))
				{
					this._CuerpoHTML = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCategoria", DbType="Int")]
		public System.Nullable<int> IdCategoria
		{
			get
			{
				return this._IdCategoria;
			}
			set
			{
				if ((this._IdCategoria != value))
				{
					this._IdCategoria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaCreacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaCreacion
		{
			get
			{
				return this._FechaCreacion;
			}
			set
			{
				if ((this._FechaCreacion != value))
				{
					this._FechaCreacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaModificacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaModificacion
		{
			get
			{
				return this._FechaModificacion;
			}
			set
			{
				if ((this._FechaModificacion != value))
				{
					this._FechaModificacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuarioAutor", DbType="Int")]
		public System.Nullable<int> IdUsuarioAutor
		{
			get
			{
				return this._IdUsuarioAutor;
			}
			set
			{
				if ((this._IdUsuarioAutor != value))
				{
					this._IdUsuarioAutor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EsDestacado", DbType="Bit")]
		public System.Nullable<bool> EsDestacado
		{
			get
			{
				return this._EsDestacado;
			}
			set
			{
				if ((this._EsDestacado != value))
				{
					this._EsDestacado = value;
				}
			}
		}
	}
	
	public partial class usp_CMS_Contenido_ListarPorCategoriaResult
	{
		
		private int _IdContenido;
		
		private string _Titulo;
		
		private string _CuerpoHTML;
		
		private System.Nullable<int> _IdCategoria;
		
		private string _Estado;
		
		private System.Nullable<System.DateTime> _FechaCreacion;
		
		private System.Nullable<System.DateTime> _FechaModificacion;
		
		private System.Nullable<int> _IdUsuarioAutor;
		
		private System.Nullable<bool> _EsDestacado;
		
		public usp_CMS_Contenido_ListarPorCategoriaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdContenido", DbType="Int NOT NULL")]
		public int IdContenido
		{
			get
			{
				return this._IdContenido;
			}
			set
			{
				if ((this._IdContenido != value))
				{
					this._IdContenido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Titulo", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string Titulo
		{
			get
			{
				return this._Titulo;
			}
			set
			{
				if ((this._Titulo != value))
				{
					this._Titulo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CuerpoHTML", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string CuerpoHTML
		{
			get
			{
				return this._CuerpoHTML;
			}
			set
			{
				if ((this._CuerpoHTML != value))
				{
					this._CuerpoHTML = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCategoria", DbType="Int")]
		public System.Nullable<int> IdCategoria
		{
			get
			{
				return this._IdCategoria;
			}
			set
			{
				if ((this._IdCategoria != value))
				{
					this._IdCategoria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaCreacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaCreacion
		{
			get
			{
				return this._FechaCreacion;
			}
			set
			{
				if ((this._FechaCreacion != value))
				{
					this._FechaCreacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaModificacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaModificacion
		{
			get
			{
				return this._FechaModificacion;
			}
			set
			{
				if ((this._FechaModificacion != value))
				{
					this._FechaModificacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuarioAutor", DbType="Int")]
		public System.Nullable<int> IdUsuarioAutor
		{
			get
			{
				return this._IdUsuarioAutor;
			}
			set
			{
				if ((this._IdUsuarioAutor != value))
				{
					this._IdUsuarioAutor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EsDestacado", DbType="Bit")]
		public System.Nullable<bool> EsDestacado
		{
			get
			{
				return this._EsDestacado;
			}
			set
			{
				if ((this._EsDestacado != value))
				{
					this._EsDestacado = value;
				}
			}
		}
	}
	
	public partial class usp_CMS_Contenido_ObtenerPorIdResult
	{
		
		private int _IdContenido;
		
		private string _Titulo;
		
		private string _CuerpoHTML;
		
		private System.Nullable<int> _IdCategoria;
		
		private string _Estado;
		
		private System.Nullable<System.DateTime> _FechaCreacion;
		
		private System.Nullable<System.DateTime> _FechaModificacion;
		
		private System.Nullable<int> _IdUsuarioAutor;
		
		private System.Nullable<bool> _EsDestacado;
		
		public usp_CMS_Contenido_ObtenerPorIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdContenido", DbType="Int NOT NULL")]
		public int IdContenido
		{
			get
			{
				return this._IdContenido;
			}
			set
			{
				if ((this._IdContenido != value))
				{
					this._IdContenido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Titulo", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string Titulo
		{
			get
			{
				return this._Titulo;
			}
			set
			{
				if ((this._Titulo != value))
				{
					this._Titulo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CuerpoHTML", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string CuerpoHTML
		{
			get
			{
				return this._CuerpoHTML;
			}
			set
			{
				if ((this._CuerpoHTML != value))
				{
					this._CuerpoHTML = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCategoria", DbType="Int")]
		public System.Nullable<int> IdCategoria
		{
			get
			{
				return this._IdCategoria;
			}
			set
			{
				if ((this._IdCategoria != value))
				{
					this._IdCategoria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaCreacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaCreacion
		{
			get
			{
				return this._FechaCreacion;
			}
			set
			{
				if ((this._FechaCreacion != value))
				{
					this._FechaCreacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaModificacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaModificacion
		{
			get
			{
				return this._FechaModificacion;
			}
			set
			{
				if ((this._FechaModificacion != value))
				{
					this._FechaModificacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuarioAutor", DbType="Int")]
		public System.Nullable<int> IdUsuarioAutor
		{
			get
			{
				return this._IdUsuarioAutor;
			}
			set
			{
				if ((this._IdUsuarioAutor != value))
				{
					this._IdUsuarioAutor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EsDestacado", DbType="Bit")]
		public System.Nullable<bool> EsDestacado
		{
			get
			{
				return this._EsDestacado;
			}
			set
			{
				if ((this._EsDestacado != value))
				{
					this._EsDestacado = value;
				}
			}
		}
	}
	
	public partial class usp_CMS_ContenidoMultimedia_AsignarResult
	{
		
		private System.Nullable<decimal> _IdContenidoMultimediaCreado;
		
		public usp_CMS_ContenidoMultimedia_AsignarResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdContenidoMultimediaCreado", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> IdContenidoMultimediaCreado
		{
			get
			{
				return this._IdContenidoMultimediaCreado;
			}
			set
			{
				if ((this._IdContenidoMultimediaCreado != value))
				{
					this._IdContenidoMultimediaCreado = value;
				}
			}
		}
	}
	
	public partial class usp_CMS_ContenidoMultimedia_ListarPorContenidoResult
	{
		
		private int _IdArchivo;
		
		private string _NombreOriginal;
		
		private string _TipoMIME;
		
		private int _IdContenidoMultimedia;
		
		public usp_CMS_ContenidoMultimedia_ListarPorContenidoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdArchivo", DbType="Int NOT NULL")]
		public int IdArchivo
		{
			get
			{
				return this._IdArchivo;
			}
			set
			{
				if ((this._IdArchivo != value))
				{
					this._IdArchivo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreOriginal", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string NombreOriginal
		{
			get
			{
				return this._NombreOriginal;
			}
			set
			{
				if ((this._NombreOriginal != value))
				{
					this._NombreOriginal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoMIME", DbType="VarChar(100)")]
		public string TipoMIME
		{
			get
			{
				return this._TipoMIME;
			}
			set
			{
				if ((this._TipoMIME != value))
				{
					this._TipoMIME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdContenidoMultimedia", DbType="Int NOT NULL")]
		public int IdContenidoMultimedia
		{
			get
			{
				return this._IdContenidoMultimedia;
			}
			set
			{
				if ((this._IdContenidoMultimedia != value))
				{
					this._IdContenidoMultimedia = value;
				}
			}
		}
	}
	
	public partial class usp_CMS_ContenidoMultimedia_ObtenerPorIdResult
	{
		
		private int _IdContenidoMultimedia;
		
		private System.Nullable<int> _IdContenido;
		
		private System.Nullable<int> _IdArchivo;
		
		public usp_CMS_ContenidoMultimedia_ObtenerPorIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdContenidoMultimedia", DbType="Int NOT NULL")]
		public int IdContenidoMultimedia
		{
			get
			{
				return this._IdContenidoMultimedia;
			}
			set
			{
				if ((this._IdContenidoMultimedia != value))
				{
					this._IdContenidoMultimedia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdContenido", DbType="Int")]
		public System.Nullable<int> IdContenido
		{
			get
			{
				return this._IdContenido;
			}
			set
			{
				if ((this._IdContenido != value))
				{
					this._IdContenido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdArchivo", DbType="Int")]
		public System.Nullable<int> IdArchivo
		{
			get
			{
				return this._IdArchivo;
			}
			set
			{
				if ((this._IdArchivo != value))
				{
					this._IdArchivo = value;
				}
			}
		}
	}
	
	public partial class usp_CMS_ContenidoRol_AsignarPermisoResult
	{
		
		private System.Nullable<decimal> _IdContenidoRolCreado;
		
		public usp_CMS_ContenidoRol_AsignarPermisoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdContenidoRolCreado", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> IdContenidoRolCreado
		{
			get
			{
				return this._IdContenidoRolCreado;
			}
			set
			{
				if ((this._IdContenidoRolCreado != value))
				{
					this._IdContenidoRolCreado = value;
				}
			}
		}
	}
	
	public partial class usp_CMS_ContenidoRol_ListarPorContenidoResult
	{
		
		private int _IdContenidoRol;
		
		private System.Nullable<int> _IdContenido;
		
		private System.Nullable<int> _IdRol;
		
		private string _Permiso;
		
		public usp_CMS_ContenidoRol_ListarPorContenidoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdContenidoRol", DbType="Int NOT NULL")]
		public int IdContenidoRol
		{
			get
			{
				return this._IdContenidoRol;
			}
			set
			{
				if ((this._IdContenidoRol != value))
				{
					this._IdContenidoRol = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdContenido", DbType="Int")]
		public System.Nullable<int> IdContenido
		{
			get
			{
				return this._IdContenido;
			}
			set
			{
				if ((this._IdContenido != value))
				{
					this._IdContenido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdRol", DbType="Int")]
		public System.Nullable<int> IdRol
		{
			get
			{
				return this._IdRol;
			}
			set
			{
				if ((this._IdRol != value))
				{
					this._IdRol = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Permiso", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Permiso
		{
			get
			{
				return this._Permiso;
			}
			set
			{
				if ((this._Permiso != value))
				{
					this._Permiso = value;
				}
			}
		}
	}
	
	public partial class usp_CMS_ContenidoRol_ObtenerPorIdResult
	{
		
		private int _IdContenidoRol;
		
		private System.Nullable<int> _IdContenido;
		
		private System.Nullable<int> _IdRol;
		
		private string _Permiso;
		
		public usp_CMS_ContenidoRol_ObtenerPorIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdContenidoRol", DbType="Int NOT NULL")]
		public int IdContenidoRol
		{
			get
			{
				return this._IdContenidoRol;
			}
			set
			{
				if ((this._IdContenidoRol != value))
				{
					this._IdContenidoRol = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdContenido", DbType="Int")]
		public System.Nullable<int> IdContenido
		{
			get
			{
				return this._IdContenido;
			}
			set
			{
				if ((this._IdContenido != value))
				{
					this._IdContenido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdRol", DbType="Int")]
		public System.Nullable<int> IdRol
		{
			get
			{
				return this._IdRol;
			}
			set
			{
				if ((this._IdRol != value))
				{
					this._IdRol = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Permiso", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Permiso
		{
			get
			{
				return this._Permiso;
			}
			set
			{
				if ((this._Permiso != value))
				{
					this._Permiso = value;
				}
			}
		}
	}
	
	public partial class usp_CMS_HistorialContenido_ListarPorContenidoResult
	{
		
		private int _IdHistorial;
		
		private System.Nullable<int> _IdContenido;
		
		private System.Nullable<int> _IdUsuario;
		
		private System.Nullable<System.DateTime> _FechaCambio;
		
		private string _Comentario;
		
		public usp_CMS_HistorialContenido_ListarPorContenidoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdHistorial", DbType="Int NOT NULL")]
		public int IdHistorial
		{
			get
			{
				return this._IdHistorial;
			}
			set
			{
				if ((this._IdHistorial != value))
				{
					this._IdHistorial = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdContenido", DbType="Int")]
		public System.Nullable<int> IdContenido
		{
			get
			{
				return this._IdContenido;
			}
			set
			{
				if ((this._IdContenido != value))
				{
					this._IdContenido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuario", DbType="Int")]
		public System.Nullable<int> IdUsuario
		{
			get
			{
				return this._IdUsuario;
			}
			set
			{
				if ((this._IdUsuario != value))
				{
					this._IdUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaCambio", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaCambio
		{
			get
			{
				return this._FechaCambio;
			}
			set
			{
				if ((this._FechaCambio != value))
				{
					this._FechaCambio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comentario", DbType="NVarChar(250)")]
		public string Comentario
		{
			get
			{
				return this._Comentario;
			}
			set
			{
				if ((this._Comentario != value))
				{
					this._Comentario = value;
				}
			}
		}
	}
	
	public partial class usp_CMS_HistorialContenido_ObtenerPorIdResult
	{
		
		private int _IdHistorial;
		
		private System.Nullable<int> _IdContenido;
		
		private System.Nullable<int> _IdUsuario;
		
		private System.Nullable<System.DateTime> _FechaCambio;
		
		private string _Comentario;
		
		public usp_CMS_HistorialContenido_ObtenerPorIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdHistorial", DbType="Int NOT NULL")]
		public int IdHistorial
		{
			get
			{
				return this._IdHistorial;
			}
			set
			{
				if ((this._IdHistorial != value))
				{
					this._IdHistorial = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdContenido", DbType="Int")]
		public System.Nullable<int> IdContenido
		{
			get
			{
				return this._IdContenido;
			}
			set
			{
				if ((this._IdContenido != value))
				{
					this._IdContenido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuario", DbType="Int")]
		public System.Nullable<int> IdUsuario
		{
			get
			{
				return this._IdUsuario;
			}
			set
			{
				if ((this._IdUsuario != value))
				{
					this._IdUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaCambio", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaCambio
		{
			get
			{
				return this._FechaCambio;
			}
			set
			{
				if ((this._FechaCambio != value))
				{
					this._FechaCambio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comentario", DbType="NVarChar(250)")]
		public string Comentario
		{
			get
			{
				return this._Comentario;
			}
			set
			{
				if ((this._Comentario != value))
				{
					this._Comentario = value;
				}
			}
		}
	}
	
	public partial class usp_CMS_HistorialContenido_RegistrarResult
	{
		
		private System.Nullable<decimal> _IdHistorialCreado;
		
		public usp_CMS_HistorialContenido_RegistrarResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdHistorialCreado", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> IdHistorialCreado
		{
			get
			{
				return this._IdHistorialCreado;
			}
			set
			{
				if ((this._IdHistorialCreado != value))
				{
					this._IdHistorialCreado = value;
				}
			}
		}
	}
	
	public partial class usp_CMS_Multimedia_CrearResult
	{
		
		private System.Nullable<decimal> _IdArchivoCreado;
		
		public usp_CMS_Multimedia_CrearResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdArchivoCreado", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> IdArchivoCreado
		{
			get
			{
				return this._IdArchivoCreado;
			}
			set
			{
				if ((this._IdArchivoCreado != value))
				{
					this._IdArchivoCreado = value;
				}
			}
		}
	}
	
	public partial class usp_CMS_Multimedia_ListarResult
	{
		
		private int _IdArchivo;
		
		private string _NombreOriginal;
		
		private string _TipoMIME;
		
		private System.Nullable<int> _IdUsuarioSubio;
		
		private System.Nullable<System.DateTime> _FechaSubida;
		
		public usp_CMS_Multimedia_ListarResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdArchivo", DbType="Int NOT NULL")]
		public int IdArchivo
		{
			get
			{
				return this._IdArchivo;
			}
			set
			{
				if ((this._IdArchivo != value))
				{
					this._IdArchivo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreOriginal", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string NombreOriginal
		{
			get
			{
				return this._NombreOriginal;
			}
			set
			{
				if ((this._NombreOriginal != value))
				{
					this._NombreOriginal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoMIME", DbType="VarChar(100)")]
		public string TipoMIME
		{
			get
			{
				return this._TipoMIME;
			}
			set
			{
				if ((this._TipoMIME != value))
				{
					this._TipoMIME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuarioSubio", DbType="Int")]
		public System.Nullable<int> IdUsuarioSubio
		{
			get
			{
				return this._IdUsuarioSubio;
			}
			set
			{
				if ((this._IdUsuarioSubio != value))
				{
					this._IdUsuarioSubio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaSubida", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaSubida
		{
			get
			{
				return this._FechaSubida;
			}
			set
			{
				if ((this._FechaSubida != value))
				{
					this._FechaSubida = value;
				}
			}
		}
	}
	
	public partial class usp_CMS_Multimedia_ObtenerPorIdResult
	{
		
		private int _IdArchivo;
		
		private string _NombreOriginal;
		
		private string _ArchivoBase64;
		
		private string _TipoMIME;
		
		private System.Nullable<int> _IdUsuarioSubio;
		
		private System.Nullable<System.DateTime> _FechaSubida;
		
		public usp_CMS_Multimedia_ObtenerPorIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdArchivo", DbType="Int NOT NULL")]
		public int IdArchivo
		{
			get
			{
				return this._IdArchivo;
			}
			set
			{
				if ((this._IdArchivo != value))
				{
					this._IdArchivo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreOriginal", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string NombreOriginal
		{
			get
			{
				return this._NombreOriginal;
			}
			set
			{
				if ((this._NombreOriginal != value))
				{
					this._NombreOriginal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ArchivoBase64", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string ArchivoBase64
		{
			get
			{
				return this._ArchivoBase64;
			}
			set
			{
				if ((this._ArchivoBase64 != value))
				{
					this._ArchivoBase64 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoMIME", DbType="VarChar(100)")]
		public string TipoMIME
		{
			get
			{
				return this._TipoMIME;
			}
			set
			{
				if ((this._TipoMIME != value))
				{
					this._TipoMIME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuarioSubio", DbType="Int")]
		public System.Nullable<int> IdUsuarioSubio
		{
			get
			{
				return this._IdUsuarioSubio;
			}
			set
			{
				if ((this._IdUsuarioSubio != value))
				{
					this._IdUsuarioSubio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaSubida", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaSubida
		{
			get
			{
				return this._FechaSubida;
			}
			set
			{
				if ((this._FechaSubida != value))
				{
					this._FechaSubida = value;
				}
			}
		}
	}
	
	public partial class usp_CMS_Rol_CrearResult
	{
		
		private System.Nullable<decimal> _IdRolCreado;
		
		public usp_CMS_Rol_CrearResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdRolCreado", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> IdRolCreado
		{
			get
			{
				return this._IdRolCreado;
			}
			set
			{
				if ((this._IdRolCreado != value))
				{
					this._IdRolCreado = value;
				}
			}
		}
	}
	
	public partial class usp_CMS_Rol_ListarResult
	{
		
		private int _IdRol;
		
		private string _NombreRol;
		
		private string _Descripcion;
		
		public usp_CMS_Rol_ListarResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdRol", DbType="Int NOT NULL")]
		public int IdRol
		{
			get
			{
				return this._IdRol;
			}
			set
			{
				if ((this._IdRol != value))
				{
					this._IdRol = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreRol", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string NombreRol
		{
			get
			{
				return this._NombreRol;
			}
			set
			{
				if ((this._NombreRol != value))
				{
					this._NombreRol = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="NVarChar(250)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
	}
	
	public partial class usp_CMS_Rol_ObtenerPorIdResult
	{
		
		private int _IdRol;
		
		private string _NombreRol;
		
		private string _Descripcion;
		
		public usp_CMS_Rol_ObtenerPorIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdRol", DbType="Int NOT NULL")]
		public int IdRol
		{
			get
			{
				return this._IdRol;
			}
			set
			{
				if ((this._IdRol != value))
				{
					this._IdRol = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreRol", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string NombreRol
		{
			get
			{
				return this._NombreRol;
			}
			set
			{
				if ((this._NombreRol != value))
				{
					this._NombreRol = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="NVarChar(250)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
	}
	
	public partial class usp_CMS_Usuario_CrearResult
	{
		
		private System.Nullable<decimal> _IdUsuarioCreado;
		
		public usp_CMS_Usuario_CrearResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuarioCreado", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> IdUsuarioCreado
		{
			get
			{
				return this._IdUsuarioCreado;
			}
			set
			{
				if ((this._IdUsuarioCreado != value))
				{
					this._IdUsuarioCreado = value;
				}
			}
		}
	}
	
	public partial class usp_CMS_Usuario_ListarResult
	{
		
		private int _IdUsuario;
		
		private string _NombreCompleto;
		
		private string _Usuario;
		
		private string _Password;
		
		private System.Nullable<System.DateTime> _UltimoLogin;
		
		public usp_CMS_Usuario_ListarResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuario", DbType="Int NOT NULL")]
		public int IdUsuario
		{
			get
			{
				return this._IdUsuario;
			}
			set
			{
				if ((this._IdUsuario != value))
				{
					this._IdUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreCompleto", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string NombreCompleto
		{
			get
			{
				return this._NombreCompleto;
			}
			set
			{
				if ((this._NombreCompleto != value))
				{
					this._NombreCompleto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				if ((this._Usuario != value))
				{
					this._Usuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this._Password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UltimoLogin", DbType="DateTime")]
		public System.Nullable<System.DateTime> UltimoLogin
		{
			get
			{
				return this._UltimoLogin;
			}
			set
			{
				if ((this._UltimoLogin != value))
				{
					this._UltimoLogin = value;
				}
			}
		}
	}
	
	public partial class usp_CMS_Usuario_ObtenerPorIdResult
	{
		
		private int _IdUsuario;
		
		private string _NombreCompleto;
		
		private string _Usuario;
		
		private string _Password;
		
		private System.Nullable<System.DateTime> _UltimoLogin;
		
		public usp_CMS_Usuario_ObtenerPorIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuario", DbType="Int NOT NULL")]
		public int IdUsuario
		{
			get
			{
				return this._IdUsuario;
			}
			set
			{
				if ((this._IdUsuario != value))
				{
					this._IdUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreCompleto", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string NombreCompleto
		{
			get
			{
				return this._NombreCompleto;
			}
			set
			{
				if ((this._NombreCompleto != value))
				{
					this._NombreCompleto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				if ((this._Usuario != value))
				{
					this._Usuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this._Password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UltimoLogin", DbType="DateTime")]
		public System.Nullable<System.DateTime> UltimoLogin
		{
			get
			{
				return this._UltimoLogin;
			}
			set
			{
				if ((this._UltimoLogin != value))
				{
					this._UltimoLogin = value;
				}
			}
		}
	}
	
	public partial class usp_CMS_Usuario_ValidarLoginResult
	{
		
		private int _IdUsuario;
		
		private string _NombreCompleto;
		
		private string _Usuario;
		
		private string _Password;
		
		private System.Nullable<System.DateTime> _UltimoLogin;
		
		private System.DateTime _UltimoLoginActualizado;
		
		public usp_CMS_Usuario_ValidarLoginResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuario", DbType="Int NOT NULL")]
		public int IdUsuario
		{
			get
			{
				return this._IdUsuario;
			}
			set
			{
				if ((this._IdUsuario != value))
				{
					this._IdUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreCompleto", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string NombreCompleto
		{
			get
			{
				return this._NombreCompleto;
			}
			set
			{
				if ((this._NombreCompleto != value))
				{
					this._NombreCompleto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				if ((this._Usuario != value))
				{
					this._Usuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this._Password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UltimoLogin", DbType="DateTime")]
		public System.Nullable<System.DateTime> UltimoLogin
		{
			get
			{
				return this._UltimoLogin;
			}
			set
			{
				if ((this._UltimoLogin != value))
				{
					this._UltimoLogin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UltimoLoginActualizado", DbType="DateTime NOT NULL")]
		public System.DateTime UltimoLoginActualizado
		{
			get
			{
				return this._UltimoLoginActualizado;
			}
			set
			{
				if ((this._UltimoLoginActualizado != value))
				{
					this._UltimoLoginActualizado = value;
				}
			}
		}
	}
	
	public partial class usp_CMS_UsuarioRol_AsignarResult
	{
		
		private System.Nullable<decimal> _IdUsuarioRolCreado;
		
		public usp_CMS_UsuarioRol_AsignarResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuarioRolCreado", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> IdUsuarioRolCreado
		{
			get
			{
				return this._IdUsuarioRolCreado;
			}
			set
			{
				if ((this._IdUsuarioRolCreado != value))
				{
					this._IdUsuarioRolCreado = value;
				}
			}
		}
	}
	
	public partial class usp_CMS_UsuarioRol_ListarPorUsuarioResult
	{
		
		private int _IdRol;
		
		private string _NombreRol;
		
		private string _Descripcion;
		
		private int _IdUsuarioRol;
		
		public usp_CMS_UsuarioRol_ListarPorUsuarioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdRol", DbType="Int NOT NULL")]
		public int IdRol
		{
			get
			{
				return this._IdRol;
			}
			set
			{
				if ((this._IdRol != value))
				{
					this._IdRol = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreRol", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string NombreRol
		{
			get
			{
				return this._NombreRol;
			}
			set
			{
				if ((this._NombreRol != value))
				{
					this._NombreRol = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="NVarChar(250)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuarioRol", DbType="Int NOT NULL")]
		public int IdUsuarioRol
		{
			get
			{
				return this._IdUsuarioRol;
			}
			set
			{
				if ((this._IdUsuarioRol != value))
				{
					this._IdUsuarioRol = value;
				}
			}
		}
	}
	
	public partial class usp_CMS_UsuarioRol_ObtenerPorIdResult
	{
		
		private int _IdUsuarioRol;
		
		private System.Nullable<int> _IdUsuario;
		
		private System.Nullable<int> _IdRol;
		
		public usp_CMS_UsuarioRol_ObtenerPorIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuarioRol", DbType="Int NOT NULL")]
		public int IdUsuarioRol
		{
			get
			{
				return this._IdUsuarioRol;
			}
			set
			{
				if ((this._IdUsuarioRol != value))
				{
					this._IdUsuarioRol = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuario", DbType="Int")]
		public System.Nullable<int> IdUsuario
		{
			get
			{
				return this._IdUsuario;
			}
			set
			{
				if ((this._IdUsuario != value))
				{
					this._IdUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdRol", DbType="Int")]
		public System.Nullable<int> IdRol
		{
			get
			{
				return this._IdRol;
			}
			set
			{
				if ((this._IdRol != value))
				{
					this._IdRol = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
